## Assuming you're:
## 1) big fan of keybase.io
## 2) using your own private key (not the one generated by KB)
## 3) don't like mulitple keys for no reason :)
## this scripts pulls your keybase PGP keys, generate ssh keys out of them
## tested on macOS 10.12

#!/bin/bash

echo "Start Export Process"

echo "Log into Keybase..."
keybase login

echo "Exporting your PGP keys..."
keybase pgp export -o keybase.public.key
keybase pgp export -s -o keybase.private.key

echo "Importing your Keybase keys..."
gpg -q --import keybase.public.key
gpg -q --allow-secret-key-import --import keybase.private.key
gpg --list-keys | grep -A1 '^pub\s*.*\/*.\s.*' | tail -n1 | awk '{$1=$1};1' > hash.key

echo "Generating RSA keys..."
gpg --export-options export-reset-subkey-passwd,export-minimal,no-export-attributes --export-secret-keys --no-armor `cat hash.key` | openpgp2ssh `cat hash.key` > id_rsa
chmod 400 id_rsa
ssh-keygen -y -f id_rsa > id_rsa.pub

echo "Cleaning up..."
rm *.key
rm hash.key

echo "Success"
